### ISSUE TITLE
Module not found: 'less-to-json-loader'

### ISSUE THREAD

**Issue by liekkas** [atroo/less-to-json-loader#2]
can't use this loader as example.

**Comment by de-robat** [comment]
Please provide a proper error log if you expect assistance. What error does ```npm install less-to-json-loader``` give if you try it?

Which Webpack Version?

**Comment by liekkas** [comment]
hi, I'm sorry to reply late.

my env as follows:
node: v6.9.1
webpack: v1.14.0

no error when install. but got the “Module not found: 'less-to-json-loader'” when compile.

by the way, I'm use [dva-cli](https://github.com/dvajs/dva-cli) to create my project.

**Comment by de-robat** [comment]
Please provide your package.json and your webpack.config.js. Ty.

**Comment by liekkas** [comment]
because I'm using [dva](https://github.com/dvajs/dva),so the package.json is very simple:
```
{
  "private": true,
  "dependencies": {
    "babel-runtime": "^6.9.2",
    "dva": "^1.2.1",
    "less-vars-loader": "^1.1.0",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.8.0",
    "roadhog": "^0.5.2"
  },
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build"
  }
}
```

**Comment by liekkas** [comment]
This is my processing steps
```
# Install
$ npm install dva-cli -g

# Create app
$ dva new myapp --demo

# Start app
$ cd myapp
$ npm install less-to-json-loader --save
// put the example code 
$ npm start
```

**Comment by de-robat** [comment]
Well, the Loader is a Webpack Loader written for webpack 1. It won't work without webpack in place. Of course you can fork it at any time, and strip out the parts that do the less processing. Keep in mind that it has to be run as a build step thoug, it requires node.js filesystem Module. GL.
